### ISSUE TITLE
supernode modus für das webinterface (im config experten modus)

### ISSUE THREAD

**Issue by horstfffl** [freifunk-flensburg/Voting#1]
idee: haken für supernode modus der die client ssid abschaltet und nur die mesh ssid an läßt.

hintergrund: für dachinstallation währe es nice wenn es die möglichkeit gäbe die client  versorgung abzuschalten um eine möglichst hohe mesh performance zu erhalten.

hendrik soll da wohl was für ffkiel gemacht haben ich versuche das mal zu finden

**Comment by bigfootDK** [comment]
Muss der normal-freifunk-dau mit einem extra häckchen/entscheidung konfrontiert werden ?
client ssid kann einfach default an sein - und jemand der einen super-node macht hat vllt auch das knowhow im wiki zu lesen wie man per SSH den client-SSID abschaltet. 

AFAIK gibts bei der neuen Kieler FW die Hendrik bastelt einen simple und advanced config mode - die client-SSID an oder aus ist im advanced/experten modus.

**Comment by svenfl** [comment]
Man könnte den Haken defaultmäßig on setzen und genauso wie bei Mesh on Wan schreiben Nur deaktivieren wenn ihr wisst was ihr tut

**Comment by horstfffl** [comment]
der normale dau sollte erst garnicht in den expertenmodus kommen :)
vielleicht sollte man dort noch ne böse warnung mit "sind sie sich sicher das sie fortfahren wollen" reinbauen :)
ich habe jetz schon mit 2 leuten gesprochen die einen guten standort haben und für die mangels ssh/openwrt kentnisse solch ein einfach einzustellender supernode-mode von vorteil währe.

generell währen ein paar erklärungen  ganz gut im webinterface für zb mesh on wan
da war letzens jemand da der hatte bei nem standard dslrouter---lan--->fffl-router aufbau meshonwan an und dann das  problem  von portscans vom freifunknetz ins private netz

**Comment by Wlanfr3ak** [comment]
Wir sollten allgemein im Wiki die bedeutung jedes einzelnen Feldes im Config Mode bebildert ausführen und aus dem Menü dorthin verlinken.

**Comment by horstfffl** [comment]
können wir auf ein anderes release vertagen weil ich den code nicht gefunden habe.
wiki könnte man zusammen mal beim treffen weiter ausbauen.
