### ISSUE TITLE
neue firmware

### ISSUE THREAD

**Issue by flemming-pr** [freifunk-flensburg/Voting#2]
Da wir schon seit längerem vor haben mal die S-1.1 ab zu lösen durch die 2014.3 habe ich mal einen neuen branch in der site von unserer firmware gemacht.
https://github.com/freifunk-flensburg/site-fffl/blob/pre-2014.3-stable-1/site.conf

Die änderungen gegen über der site von der s-1.1 sind folgende:

Die fastd methode wurde umgestellt diese verspricht einen höeren daten durchsatz.
  ist eingeschaltet auf urbach und gw02 

Fastd key für gw02 wurde aktualisiert 
  bedeutet nach dem update haben alle knoten wieder zwei vpn links und nicht wie jetzt nur einen da snowden weggefallen ist.

Den Sendekanal vom 2,4ghz band habe ich wieder zurück auf kanal 1 gesetzt und nicht wie ursprücglich geplant auf kanal 9.
Der grund den ich sehen ist der, dass unser update system etwas instabiel ist und wir jetzt erstmal durch ein erstes update wieder 
knoten an alle gateways anbinden. 

und der letzte punkt betrifft die signaturen die unter eine neue firmware kommt.
dort hatten wir eigentlich geplant 3 aus 6 müssen richtig sein.
Ich habe das gefühl, dass 6 signaturen das ganze verkomplizieren und noch mehr spiel für fehler entstehen. 
außerdem haben die meisten anderen communyties auch meist nur 2 aus 3 .
desweiteren sind wir momentan (zumindest habe ich das gefühl) nur 3 Leute dich sich intensiev mit der firmware befassen 

Außerdem solltn wir das update möglichst bald fahren da in der neuen firmware auch neue hardware unterstützt wird wie z.b. die cpe's von tp-link und noch einige andere mehr

Alternative Version von Fabian: https://github.com/freifunk-flensburg/site-fffl/pull/5
Zusätzlich wäre noch Interessant ob 5 GHz einen anderen Namen bekommt um die Verbindung auch nur mit 5 GHz für Clients möglich zu machen

**Comment by horstfffl** [comment]
mach lieber aus den einzelnen änderungen jeweils ein issue.
dazu sollte dann auch ein issue rein das du signing keys löschen bzw hinzufügen möchtest da du das im text hier nicht erwähnst. die einzelnen issues können dann alle einen milestone mit namen  des nächsten releases bekommen.

**Comment by svenfl** [comment]
Ich würde den Releasnamen auf 2014.4 festlegen da die neue Version auf Gluon 2014.4 basiert
