### ISSUE TITLE
Nodegame

### ISSUE THREAD

**Issue by tr4ce** [freifunk-flensburg/Voting#9]
Moin Moin,

ich habe neulich das "Nodegame" ( https://wiki.luebeck.freifunk.net/Nodegame / http://wiesbaden.freifunk.net/2014/06/07/nodegame.html ) entdeckt. Wäre das auch nicht auch was für unsere schöne Freifunk Flensburg Community? :) 

Viele Grüße,

trace

**Comment by horstfffl** [comment]
find ich gut. du hast da ja schon mal testweise nen server laufen :)

**Comment by flemming-pr** [comment]
soweit ich das richtig sehe im git brauchst du ja nur die nodes.jason dazu und an die kommst du ja einfach so ran. 
https://github.com/apirogov/ffnodegame
kannst du ja mal test weise bauen

**Comment by tr4ce** [comment]
Schon geschehen...läuft testweise hier http://10.129.34.92:3000/ ( nur intern zu erreichen )

![screenshot 2015-03-29 at 20 16 49](https://cloud.githubusercontent.com/assets/11424049/6886931/9ce84df2-d650-11e4-94a2-bf24f84b53c7.png)

**Comment by roikiermedia** [comment]
Finde ich eine nette Idee. Ob FFFL das ganze offiziell betreibt oder es von dir weiter intern gemacht wird finde ich egal. Ist aber schön damit wieder einen neuen Dienst zu haben.

**Comment by foertel** [comment]
-1

Ich bin in keinster Weise gegen das Nodegame, aber dagegen, dass die Community das als Dienst betreibt. Die Community hat genug zu schaffen, den Dienst sollte jemand frei betreiben.

**Comment by tr4ce** [comment]
Interessanter Einwand. Könntest du das genauer erläutern? Die Community sind doch alle, die Freifunk aktiv und passiv unterstützen. Mein persönlicher Beitrag wäre unter anderem, diesen Dienst zu betreuen.

Falls du meinst, dass das Hauptaugenmerk des Freifunkes nicht auf dem Dienst an sich beruhen sollte, da stimme ich dir zu.

**Comment by bigfootDK** [comment]
-+0
Nodegame ist eine nette spielerei. Wenn jemand lust hat diesen service zu betreiben ist es okay. Egal ob nu privat oder auf vereins hardware.

**Comment by foertel** [comment]
@tr4ce um den dienst zu betreiben, brauchst du kein voting. ;-) mach einfach, wir freuen uns über jeden dienst!

in den votings geht es um dinge, auf die "die community" (richtig, da gehören alle dazu, deswegen ist das voting ja auch offen) betreibt - auf eigener hardware und eigener verantwortung.

wenn du den dienst privat betreiben möchtest, dann nur los. ;-) ich werde ihn in mein wallboard einbauen und regelmäßig mal drauf gucken. ;-) aber dann kann das voting hier zurückgezogen werden, weil es dann die community infrastruktur nicht betrifft.

**Comment by Wlanfr3ak** [comment]
Ich bin für das Nodegame egal wo es läuft aber: Dienste zu betreiben sollte auch verantwortungsvoll umgesetzt werden und zur Not an andere deligiert werden. Es wäre schade wenn ein Service ensteht dem viele Vertrauen und der dann ungepflegt einschlafen würde.
